AWSTemplateFormatVersion: 2010-09-09
Description: Sample New Relic Dashboards Template
Resources:
  Resource1:
    Type: 'NewRelic::Observability::Dashboards'
    Properties:
      Dashboard: >-
        dashboard: {description: "CloudFormation test dashboard", name: "CloudFormation Test Dashboard", pages: 
          {description: "TD PAGE", name: "TD Page", widgets: 
            {title: "Widget Title", configuration: 
              {markdown: {text: "Some markdown"}}}}, permissions: PRIVATE}
      Tags:
        CreateTag1Key1: "CreateTag1Value1"

Outputs:
  CustomResourceGuid:
    Value: !GetAtt Resource1.Guid
